config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :kittens

  root 'kittens#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten Created"
      redirect_to kitten_path(@kitten)
    else
      flash.now[:danger] = "Everytime a field is filled out incorrectly, a " +
                           "kitten gets put out on the street"
      render :new
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update_attributes(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten Updated"
      redirect_to kitten_path(@kitten)
    else
      flash.now[:danger] = "Everytime a field is filled out incorrectly, a " +
                           "kitten gets put out on the street"
      render :edit
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    redirect_to root_url
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten, url: yield(:form_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %>

  <%= f.label :softness %>
  <%= f.text_field :softness %>

  <%= f.submit yield(:button_text) %>

<% end %>

app/views/kittens/_kitten.html.erb
<li>
  <%=link_to kitten.name, kitten_path(kitten) %><br>
  Age: <%= kitten.age %><br>
  Cuteness: <%= kitten.cuteness %><br>
  Softness: <%= kitten.softness %>
  <%= form_for kitten, html: { method: :delete } do |f| %>
    <%= f.submit "Kill this kitten" %>
  <% end %>
</li>

app/views/kittens/edit.html.erb
<% provide(:form_path, kitten_path) %>
<% provide(:button_text, "Save updates") %>
<h1>Upgrade this Kitten</h1>
<%= render 'kittens/form' %>
<%= form_for @kitten, html: { method: :delete } do |f| %>
  <%= f.submit "Kill this kitten" %>
<% end %>

app/views/kittens/index.html.erb
<%= link_to "Add New Kitten", new_kitten_path %>

<h2>All Kittens</h2>
<ol class="kittens">
   <%= render @kittens %>
</ol>

app/views/kittens/new.html.erb
<% provide(:form_path, kittens_path) %>
<% provide(:button_text, "Save this lil guy!") %>
<h1>Add a new Kitten</h1>
<%= render 'kittens/form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<h3>Age: <%= @kitten.age %></h3>
<h3>Cuteness: <%= @kitten.cuteness %></h3>
<h3>Softness: <%= @kitten.softness %></h3>
<%= link_to "Edit", edit_kitten_path %>
<%= form_for @kitten, html: { method: :delete } do |f| %>
  <%= f.submit "Kill this kitten" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "Home", root_url %>
    </header>
    <%= yield %>
  </body>
</html>